---
title: "Tarea_Programada_02_Jarel_Tenorio"
author: "Jarel Tenorio"
date: "2024-06-06"
output: html_document
---

# Parte 4: ejercicios de programación

### Carga y Exploración de Datos
```{r}
# Se carga el conjunto de dados en una variable llamada "mtcars" y se usa attach para poder usar las varibales sin tener que usar el $
mtcars=mtcars
attach(mtcars)
# Se imprimen las primeras 5 filas y tambien las 5 ultimas
head(mtcars,5)
tail(mtcars,5)
# Se usa la funcion str para la estructura y el tipo de cada variable
str(mtcars)
# Se usa la funcion summary para ver un resumen estadistico de cada una de las variables numericas
summary(mtcars)
```

### Visualización de Datos
```{r}
# Se crea un histograma con la variable mpg
hist(mpg, main = "Histograma de MPG",
     xlab= "Millas por Galon",
     ylab= "Frecuencia",
     xlim=c(8,37), col= "purple",
     freq=TRUE)
```

```{r warning=FALSE}
# Se crea un boxplot para comparar la distribucion entre mpg y cyl
boxplot(mpg~cyl, main= "Diagrama de Caja",
        xlab="Millas por Galon",
        ylab="Cilindraje",
        col="blue",border="red",
        horizontal=TRUE,notch=TRUE)
```

```{r}
# Se crea un diagrma de dispersion para ver la relacion entre hp y mpg
plot(hp,mpg,
     main="Diagrama de Dispersion",
     xlab = "Caballos de Fuerza",
     ylab = "Millas por Galon", pch=20)
```

```{r}
# Se crea el grafico de barras para mostrar el numero de automoviles en cada categoria de cilindros
cantidad_cilindraje=table(cyl)
barplot(cantidad_cilindraje, main = "Cantidad de Automoviles Segun su Cilindraje",
        xlab= "Cantidad de Automoviles",
        ylab="Numero de Cilindros",
        col = "aquamarine2",
        horiz = TRUE)
```

### Estadística Descriptiva
```{r}
# Se calcula la media, mediana, varianza y desviacion estandar de la variable mpg
estadistica_descriptiva_mpg=data.frame(mediana=median(mpg),
                                       media=round(mean(mpg),2),
                                       varianza=round(var(mpg),2),
                                       desvest=round(sd(mpg),2))
t(estadistica_descriptiva_mpg)
```

```{r}
# Se crea latabla de contingencia con las variables cyl y gear
tabla_contingencia=table(cyl,gear)
tabla_contingencia # Las columnas son el numero de marchas y las filas el numero de cilindraje
```

### Estadística Inferencial
```{r}
t.test(mpg, mu=20)
```

```{r}
cor.test(hp,mpg, method = "pearson")
```

